job_id: 0

defaults:
  - data: mice
  - model: disrnn
  - _self_

# Global random seed
seed: 42

# W&B logging
wandb:
  entity: AIND-disRNN  # W&B entity/team name (don't overwrite)
  dir: /results  # Directory to store wandb files locally in the capsule (don't overwrite)
  project: test  # Please set your own project name here!
  name: ${data.run_name_component}_${model.run_name_component}  # Consist of data and model parts


# Hydra output directories to be distributed to the wrapper capsule
hydra:
  job:
    chdir: true
  run:
    # Directory for single runs, where the user provides the job id
    dir: /results/${job_id}/
  sweep:
    # Directory for multirun sweeps, where Hydra manages job ids
    dir: /results/
