job_id: 0

defaults:
  - data: mice
  - model: disrnn
  - _self_

seed: 42

# Hydra output directories
hydra:
  run:
    # Directory for single runs, where the user provides the job id
    dir: /root/capsule/results/jobs/${job_id}
  sweep:
    # Directory for multirun sweeps, where Hydra manages job ids
    dir: /root/capsule/results/jobs

